name: Sequential Jobs Workflow  # Имя

on:  # Когда? При пуше в main
  push:
    branches: [ main ]

jobs:  # Три работы по очереди
  build:  # Первая: "сборка"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build step
        run: |
          echo "Building the project..."  # Пишет "Собираю проект..."
          sleep 5  # Ждёт 5 секунд (симуляция)

  test:  # Вторая: "тесты" — запускается ТОЛЬКО после build
    runs-on: ubuntu-latest
    needs: build  # Зависит от build — ждёт, пока build закончится успешно
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test step
        run: |
          echo "Running tests..."  # Пишет "Запускаю тесты..."
          sleep 3  # Ждёт 3 секунды

  deploy:  # Третья: "деплой" — после test
    runs-on: ubuntu-latest
    needs: test  # Зависит от test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy step
        run: |
          echo "Deploying to production..."  # Пишет "Разворачиваю в продакшн..."
          sleep 2  # Ждёт 2 секунды
